# http://docs.travis-ci.com/user/languages/r/

language: r

#to avoid ERROR: dependency ‘V8’ is not available for package ‘geojsonio’
before_install:
#  - sudo apt-get install libv8-dev
#to avoid sudo error
sudo: required  

warnings_are_errors: true

r_binary_packages:
 - rgdal
 - rmarkdown
 
r_github_packages: 
 - ropensci/geojsonio

